changes : deployment stashes only for relevant directories

diff --git a/.github/workflows/admin-fr-deployment.yml b/.github/workflows/admin-fr-deployment.yml
--- a/.github/workflows/admin-fr-deployment.yml
+++ b/.github/workflows/admin-fr-deployment.yml
@@ -32,15 +32,15 @@ jobs:
                   script: |
                       echo "SSH actions starting...🔰🔰🔰"
                       cd "${{env.project_dir}}" && echo "Moved to directory"
-                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      cd "apps/admin-fr" && echo "Moved to admin-fr directory"
+                      git stash push -m "admin-fr stashed" -- 'apps/admin-fr/*' && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       git fetch origin "${{github.ref_name}}" && git checkout "${{github.ref_name}}" && echo "Fetched latest changes ✅" || echo "Fetch latest changes failed ❌"
                       git pull origin "${{github.ref_name}}" && echo "Pulled latest ✅" || echo "Pull latest failed ❌"
                       chmod +x build-script.sh && echo "Build script executable set ✅" || echo "Failed to set build script executable ❌"
                       chmod +x script.sh && echo "Serve script executable set ✅" || echo "Failed to set serve script executable ❌"
                       npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
-                      npm run build-dev --workspace=admin-fr && echo "Build files ✅" || echo "NPM Build failed ❌
-                      cd "apps/admin-fr" && echo "Moved to admin-fr directory"
+                      npm run build-dev --workspace=admin-fr && echo "Build files ✅" || echo "NPM Build failed ❌"
                       pm2 startOrRestart pm2.json && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
                       echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
-                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      git stash push -m "admin-fr stashed" -- 'apps/admin-fr/*' && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       echo "SSH actions Ended ✅"
