fix : deployment workflows action triggers

diff --git a/.github/workflows/admin-fr-deployment.yml b/.github/workflows/admin-fr-deployment.yml
--- a/.github/workflows/admin-fr-deployment.yml
+++ b/.github/workflows/admin-fr-deployment.yml
@@ -1,4 +1,4 @@
-name: Auto-Deployment
+name: Admin-Frontend-Deployment
 on:
     workflow_run:
         workflows: ["Packages-Build"]
@@ -6,6 +6,10 @@ on:
             - completed
 jobs:
     auto-deploy:
+        if: >
+            github.event.workflow_run.conclusion == 'success' &&
+            github.event.workflow_run.head_branch == 'dev'
+
         runs-on: ubuntu-latest
         env:
             pm2_name: "ps-fr-admin"
@@ -35,8 +39,8 @@ jobs:
                       chmod +x script.sh && echo "Serve script executable set ✅" || echo "Failed to set serve script executable ❌"
                       npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
                       npm run build-dev --workspace=admin-fr && echo "Build files ✅" || echo "NPM Build failed ❌
-                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       cd "apps/admin-fr" && echo "Moved to admin-fr directory"
                       pm2 startOrRestart pm2.json && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
                       echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
+                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       echo "SSH actions Ended ✅"
diff --git a/.github/workflows/crm-fr-deployment.yml b/.github/workflows/crm-fr-deployment.yml
--- a/.github/workflows/crm-fr-deployment.yml
+++ b/.github/workflows/crm-fr-deployment.yml
@@ -1,4 +1,4 @@
-name: Auto-Deployment
+name: CRM-Frontend-Deployment
 on:
     workflow_run:
         workflows: ["Packages-Build"]
@@ -6,11 +6,15 @@ on:
             - completed
 jobs:
     auto-deploy:
+        if: >
+            github.event.workflow_run.conclusion == 'success' &&
+            github.event.workflow_run.head_branch == 'dev'
+
         runs-on: ubuntu-latest
         env:
             pm2_name: "ps-crm-fr"
             project_dir: "/home/${{ secrets.USERNAME }}/htdocs/pridespaces/monorepo"
-            script-name: "build-dev"
+            script-name: "build"
 
         steps:
             - uses: actions/checkout@v4
@@ -34,9 +38,9 @@ jobs:
                       chmod +x build-script.sh && echo "Build script executable set ✅" || echo "Failed to set build script executable ❌"
                       chmod +x script.sh && echo "Serve script executable set ✅" || echo "Failed to set serve script executable ❌"
                       npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
-                      npm run build-dev --workspace=ps-crm && echo "Build files ✅" || echo "NPM Build failed ❌"
-                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      npm run build -- --filter=ps-crm && echo "Build files ✅" || echo "NPM Build failed ❌"
                       cd "apps/ps-crm" && echo "Moved to ps-crm directory"
                       pm2 startOrRestart pm2.json && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
                       echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
+                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       echo "SSH actions Ended ✅"
