fix : workflows stash paths

diff --git a/.github/workflows/backend-deployment.yml b/.github/workflows/backend-deployment.yml
--- a/.github/workflows/backend-deployment.yml
+++ b/.github/workflows/backend-deployment.yml
@@ -53,13 +53,13 @@ jobs:
                   script: |
                       echo "SSH actions starting...🔰🔰🔰"
                       cd "${{env.project_dir}}" && echo "Moved to directory"
-                      git stash push -m "backend stashed" -- 'apps/backend/*' && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       git checkout "${{github.ref_name}}" && echo "Checked out branch ✅" || echo "Checkout failed ❌"
                       git pull origin "${{github.ref_name}}" && echo "Pulled latest ✅" || echo "Pull latest failed ❌"
                       npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
                       npm run build -- --filter=backend && echo "Build files ✅" || echo "NPM Build failed ❌"
                       pm2 startOrRestart pm2.json && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
                       echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
-                      git stash push -m "backend stashed" -- 'apps/backend/*' && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       git stash clear && echo "Stashed changes cleared ✅" || echo "Stash clear failed ❌"
                       echo "SSH actions Ended ✅"
diff --git a/.github/workflows/crm-fr-deployment.yml b/.github/workflows/crm-fr-deployment.yml
--- a/.github/workflows/crm-fr-deployment.yml
+++ b/.github/workflows/crm-fr-deployment.yml
@@ -33,7 +33,7 @@ jobs:
                       echo "SSH actions starting...🔰🔰🔰"
                       cd "${{env.project_dir}}" && echo "Moved to directory"
                       cd "apps/ps-crm" && echo "Moved to ps-crm directory"
-                      git stash push -m "crm-fr stashed" -- 'apps/ps-crm/*' && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       git fetch origin "${{github.ref_name}}" && git checkout "${{github.ref_name}}" && echo "Fetched latest changes ✅" || echo "Fetch latest changes failed ❌"
                       git pull origin "${{github.ref_name}}" && echo "Pulled latest ✅" || echo "Pull latest failed ❌"
                       chmod +x build-script.sh && echo "Build script executable set ✅" || echo "Failed to set build script executable ❌"
@@ -42,5 +42,5 @@ jobs:
                       npm run build -- --filter=ps-crm && echo "Build files ✅" || echo "NPM Build failed ❌"
                       pm2 startOrRestart pm2.json && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
                       echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
-                      git stash push -m "crm-fr stashed" -- 'apps/ps-crm/*' && echo "Stashed changes ✅" || echo "Stash failed ❌"
+                      git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
                       echo "SSH actions Ended ✅"
