workflow - dev deployment added

diff --git a/.github/workflows/dev-deployment.yml b/.github/workflows/dev-deployment.yml
--- a/.github/workflows/dev-deployment.yml
+++ b/.github/workflows/dev-deployment.yml
@@ -1,4 +1,4 @@
-name: Auto-Deployment
+name: Dev-Deployment
 on:
   push:
     branches:
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       project_dir: "/home/${{ secrets.USERNAME }}/htdocs/pridespaces/backend"
-      pm2_name: "ps-backend"
+      pm2_name: "ps-backend-dev"
 
     steps:
       - uses: actions/checkout@v4
@@ -50,8 +50,12 @@ jobs:
             cd "${{env.project_dir}}" && echo "Moved to directory"
             git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
             git pull origin "${{github.ref_name}}" && echo "Pulled latest ✅" || echo "Pull latest failed ❌"
+            git checkout "${{github.ref_name}}" && echo "Checked out branch ✅" || echo "Checkout failed ❌"
             npm i && echo "NPM Packages installed ✅" || echo "NPM packages installation failed ❌"
             npm run build && echo "Build files ✅" || echo "NPM Build failed ❌"
             pm2 restart "${{env.pm2_name}}" && echo "PM2 restarted ✅" || echo "PM2 restart failed ❌"
             echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart nginx && echo "Nginx restarted ✅" || echo "Nginx restart failed ❌"
+            git stash && echo "Stashed changes ✅" || echo "Stash failed ❌"
+            git stash clear && echo "Stashed changes cleared ✅" || echo "Stash clear failed ❌"
+            git checkout main
             echo "SSH actions Ended ✅"
